name: Hello Github Actions

run-name: ðŸš€ Hello-world.yml

on:
  push: # Lorsqu'on push un commit
    branches: [main]
  # pull_request:
  #   branches: [main]
  workflow_dispatch:
  # schedule:
  # - cron: "0 10 * * 1" # tous les lundis Ã  10h

jobs:
  say-hello:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage d'un message
        run: echo "Hello Github Actions depuis le workflow !"
