name: Push Trigger
run-name: ðŸš€ Push.yml
on:
  push:
    branches:
      - main

jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
      - name: Affichage des infos systÃ¨me
        run: |
          echo "DÃ©clenchÃ© par PUSH"
          uname -a
          whoami
          env | sort