name: Cron Job

run-name: üöÄ Schedule.yml

on:
  schedule:
    - cron: '*/5 * * * *' # toutes les 5 minutes (√† ajuster en r√©el)
  workflow_dispatch:

jobs:
  cron-job:
    runs-on: ubuntu-latest
    steps:
      - name: Ex√©cution planifi√©e
        run: echo "Ce workflow est lanc√© automatiquement via CRON."